a_core/urls.py
from django.contrib import admin
from django.urls import path, include
from a_posts.views import *
from a_users.views import *
from django.conf import settings
from a_users.views import profile_view
from django.conf.urls.static import static 
from videos import views as video_views

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('theboss/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', home_view, name='home'),
    path('category/<tag>/', home_view, name='category'),
    path('post/create/', post_create_view, name='post-create'),
    path('post/delete/<pk>/', post_delete_view, name='post-delete'),
    path('post/edit/<pk>/', post_edit_view, name='post-edit'),
    path('post/<pk>/', post_page_view, name='post'),
    path('post/like/<pk>/', like_post, name='like-post'),
    path('comment/like/<pk>/', like_comment, name='like-comment'),
    path('reply/like/<pk>/', like_reply, name='like-reply'),
    path('profile/', profile_view, name='profile'),
    path('inbox/', include('a_inbox.urls')),
    path('<username>/', profile_view, name='userprofile'),
    path('profile/edit/', profile_edit_view, name='profile-edit'),
    path('profile/delete/', profile_delete_view, name='profile-delete'),
    path('profile/onboarding/', profile_edit_view, name='profile-onboarding'),
    path('commentsent/<pk>/', comment_sent, name='comment-sent'),
    path('comment/delete/<pk>/', comment_delete_view, name='comment-delete'),
    path('reply-sent/<pk>/', reply_sent, name='reply-sent'),
    path('reply/delete/<pk>/', reply_delete_view, name='reply-delete'),
    path('templates/video/', video_views.Index.as_view(), name='index' ),
    path('videos/', include('videos.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a_inbox/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', inbox_view, name="inbox"),
    path('c/<conversation_id>/', inbox_view, name="inbox"),
    path('search_users/', search_users, name="inbox-searchusers"),
    path('new_message/<recipient_id>', new_message, name="inbox-newmessage"),
    path('new_reply/<conversation_id>', new_reply, name="inbox-newreply"),
    path('notify/<conversation_id>', notify_newmessage, name="notify-newmessage"),
    path('notify-inbox/', notify_inbox, name="notify-inbox"),
]

a_inbox/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.timesince import timesince
from cryptography.fernet import Fernet
from django.conf import settings
import uuid

class InboxMessage(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE,  related_name='sent_messages')
    conversation = models.ForeignKey('Conversation', on_delete=models.CASCADE, related_name='messages')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    @property
    def body_decrypted(self):
        f = Fernet(settings.ENCRYPT_KEY)
        message_decrypted = f.decrypt(self.body)
        message_decoded = message_decrypted.decode('utf-8')
        return message_decoded

    class Meta:
        ordering = ['-created']

    def __str__(self):
        time_since = timesince(self.created, timezone.now())
        return f'[{self.sender.username} : {time_since} ago]'


class Conversation(models.Model):
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    participants = models.ManyToManyField(User, related_name='conversations')
    lastmessage_created = models.DateTimeField(default=timezone.now)
    is_seen = models.BooleanField(default=False)

    class Meta:
        ordering = ['-lastmessage_created']

    def __str__(self):
        user_names = ", ".join(user.username for user in self.participants.all())
        return f'[{user_names}]'

a_inbox/forms.py
from django.forms import ModelForm
from django import forms
from .models import InboxMessage

class InboxNewMessageForm(ModelForm):
    class Meta:

        model = InboxMessage 
        fields = ['body']
        labels = {
            'body' : '',
        }
        widgets = {
            'body' : forms.Textarea(attrs={'rows': 4, 'placeholder': 'Add message ...'}),
        }

a_inbox/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from django.db.models import Q
from a_users.models import Profile
from cryptography.fernet import Fernet
from django.conf import settings
from .forms import InboxNewMessageForm
from .models import *

f = Fernet(settings.ENCRYPT_KEY)

@login_required
def inbox_view(request, conversation_id=None):
    my_conversations = Conversation.objects.filter(participants=request.user)
    if conversation_id:
        conversation = get_object_or_404(my_conversations, id=conversation_id)
        latest_message = conversation.messages.first()
        if conversation.is_seen == False and latest_message.sender != request.user:
            conversation.is_seen = True
            conversation.save()
    else:

        conversation = None
    context = {
        'conversation' : conversation,
        'my_conversations' : my_conversations
    }
    return render(request, 'a_inbox/inbox.html', context)


def search_users(request):
    letters = request.GET.get('search_user')
    if request.htmx:
        if len(letters) > 0:
            profiles = Profile.objects.filter(realname__icontains=letters).exclude(realname=request.user.profile.realname)
            users_id = profiles.values_list('user', flat=True)
            users = User.objects.filter(
                Q(username__icontains=letters) | Q(id__in=users_id)
            ).exclude(username=request.user.username)
            return render(request, 'a_inbox/list_searchuser.html', { 'users' : users })
        else:
            return HttpResponse('')
    else:
        raise Http404
    
@login_required
def new_message(request, recipient_id):
    recipient = get_object_or_404(User, id=recipient_id)
    new_message_form = InboxNewMessageForm()

    if request.method == 'POST':
        form = InboxNewMessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)

            message_original = form.cleaned_data['body']
            message_bytes = message_original.encode('utf-8')
            message_encrypted = f.encrypt(message_bytes)
            message_decoded = message_encrypted.decode('utf-8')
            message.body = message_decoded


            message.sender = request.user

            my_conversations = request.user.conversations.all()
            for c in my_conversations:
                if recipient in c.participants.all():
                    message.conversation = c
                    message.save()
                    c.lastmessage_created = timezone.now()
                    c.is_seen = False
                    c.save()
                    return redirect('inbox', c.id)
            new_conversation = Conversation.objects.create()
            new_conversation.participants.add(request.user, recipient)
            new_conversation.save()
            message.conversation = new_conversation
            message.save()
            return redirect('inbox', new_conversation.id)

    context = {
        'recipient' : recipient,
        'new_message_form' : new_message_form
    }
    return render(request, 'a_inbox/form_newmessage.html', context)

@login_required
def new_reply(request, conversation_id):
    new_message_form = InboxNewMessageForm()
    my_conversations = request.user.conversations.all()
    conversation = get_object_or_404(my_conversations, id=conversation_id)

    if request.method == 'POST':
        form = InboxNewMessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)

            message_original = form.cleaned_data['body']
            message_bytes = message_original.encode('utf-8')
            message_encrypted = f.encrypt(message_bytes)
            message_decoded = message_encrypted.decode('utf-8')
            message.body = message_decoded

            message.sender = request.user
            message.conversation = conversation
            message.save()
            conversation.lastmessage_created = timezone.now()
            conversation.is_seen = False
            conversation.save()
            return redirect('inbox', conversation.id)


    context = {
        'new_message_form' : new_message_form,
        'conversation' : conversation
    }
    return render(request, 'a_inbox/form_newreply.html', context)

def notify_newmessage(request, conversation_id):
    conversation = get_object_or_404(Conversation, id=conversation_id)
    latest_message = conversation.messages.first()
    if conversation.is_seen == False and latest_message.sender != request.user:
        return render(request, 'a_inbox/notify_icon.html')
    else:
        return HttpResponse('')


def notify_inbox(request):
    my_conversations = Conversation.objects.filter(participants=request.user, is_seen=False)
    for c in my_conversations:
        latest_message = c.messages.first()
        if latest_message.sender != request.user:
            return render(request, 'a_inbox/notify_icon.html')
    return HttpResponse('')

a_inbox/templates/a_inbox/conversation.html
<div id='conversation' class="col-span-4 sm:col-span-3 opacity-0 flex flex-col bg-white rounded-r-2xl pt-10 relative overflow-y-auto"
_="on load wait for 5ms then remove .opacity-0">

{% if conversation %}
<div class="text-center flex flex-col items-center">
    {% for participant in conversation.participants.all %}
    {% if participant != request.user %}
    <a href="{% url 'userprofile' participant.username %}">
        <img class="w-24 h-24 rounded-full object-cover mb-4" src="{{ participant.profile.avatar }}" />
    </a>
    <div class="text-center max-w-md">
        <h1 class="text-lg">{{ participant.profile.name }}</h1>
        <div class="text-gray-400 mb-2 -mt-5 text-sm">@{{ participant.username }}</div>
    </div>
    {% endif %}
    {% endfor %}
</div>

<ul id='inbox_messages' class="flex flex-col justify-end grow gap-6 p-4 sm:p-10 pb-0">
    {% for message in conversation.messages.all reversed %}
    <li>
        <div class="flex flex-col md:flex-row gap-1 md:gap-6">
            <a class="contents" href="{% url 'userprofile' message.sender.username %}">
                <img class="w-14 h-14 object-cover rounded-full" src="{{ message.sender.profile.avatar }}">
            </a>
            <div class="bg-white p-4 w-full rounded-xl border-2 border-gray-200">
                <div class="flex flex-col md:flex-row justify-between text-xs pb-3 text-zinc-500">
                    <div>
                        <span class="font-bold text-base text-black mr-1">{{ message.sender.profile.name }}</span>@{{ message.sender.username }}
                    </div>
                    <div>{{ message.created }} ({{ message.created|timesince }})</div>
                </div>
                <div><p class="whitespace-pre-wrap">{{ message.body_decrypted }}</p></div>
            </div>
        </div>
    </li>
    {% endfor %}

<div class="sticky bottom-0 z-1 px-4 sm:px-10 pt-6 pb-10 flex bg-white">
    <a class="flex cursor-pointer items-center gap-2 bg-gray-800 hover:bg-indigo-600 text-white rounded-full px-6 pr-8 py-3"
    hx-get="{% url 'inbox-newreply' conversation.id %}"
    hx-target="this"
    hx-swap="outerHTML scroll:#conversation:bottom" >
        <img class="h-6" src="https://img.icons8.com/material/96/ffffff/reply-arrow--v1.png">
        <div class="text-white rounded-full">Reply</div>
    </a>
</div>
 {% else %}
 <div class="h-full flex items-center justify-center text-gray-500 -mt-6 text-center p-10">
 Select a conversation or create a new message
</div>
 {% endif %}
</div>

a_inbox/templates/a_inbox/form_newmessage.html
<div class="flex gap-2 items-center mb-5">
    <span class="font-bold">To:</span>
    <div class="flex items-center gap-1">
        <img class="w-10 h-10 object-cover rounded-full mr-1" src="{{ recipient.profile.avatar }}">
        <div class="font-bold">{{ recipient.profile.name }}
            <span class="text-xs font-normal text-zinc-500">@{{ recipient.username }} </span>
        </div>
    </div>
</div>

<div class="mb-5">
    <form method='POST' action="{% url 'inbox-newmessage' recipient.id %}">
        {% csrf_token %}
        {{ new_message_form }}
        <!-- <textarea name="body" cols="40" rows="3" placeholder="Add message ..." class="text-base" required="" id="id_body"></textarea> -->
        <button type="submit" class="mt-1">Submit Message</button>
        <a @click="modal_open = false" href="{{ request.META.HTTP_REFERER }}" class="button secondaryAction ml-1 cursor-pointer" 
           _="on click reset() the closest <form/>">Cancel</a>
    </form>
</div>

a_inbox/templates/a_inbox/form_newreply.html
<div class="flex flex-col md:flex-row gap-1 md:gap-6 w-full">
    <img class="w-14 h-14 object-cover rounded-full" src="{{ user.profile.avatar }}">
    <form method='POST' action="{% url 'inbox-newreply' conversation.id %}" class="w-full">
        {% csrf_token %}
        {{ new_message_form }}
        <div class="flex justify-between">
            <button type="submit" class="mt-1">Send Message</button>
            <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
        </div>
    </form>
</div>

a_inbox/templates/a_inbox/form_searchuser.html
<h3 class="text-xl font-bold mb-4" id="modal-title">
    New Message
</h3>
<div id="new-message">
    <div class="flex gap-2 items-center">
        <span class="font-bold">To:</span>
        <input class="p-3 w-screen lg:full" placeholder="Search user ..." type="text" name="search_user"
        hx-get="{% url 'inbox-searchusers' %}"
        hx-trigger="keyup changed"
        hx-target="#search-results"
        hx-swap="innerHTML" >
    </div>
    <div id="search-results" class="block h-60 overflow-y-auto">
    </div>
</div>

a_inbox/templates/a_inbox/inbox.html
{% extends 'layouts/d.html' %}
{% load static %}

{% block content %}

<inbox class="grid grid-cols-5 sm:grid-cols-4 h-[calc(100vh-8rem)] md:h-[calc(100vh-12rem)] shadow-2xl rounded-2xl mx-1 lg:mx-10 xl:mx-48">
    <div x-data="{ modal_open: false }" class="col-span-1 bg-slate-10 rounded-l-2xl p-2 overflow-y-auto">

        <div class="p-0 sm:p-4 mb-3 sticky top-0 z-10">
            <a @click="modal_open = true" class="flex cursor-pointer items-center justify-center h-14 sm:h-16 gap-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-full">
                <img class="h-6 m-auto lg:m-0" src="https://img.icons8.com/external-anggara-glyph-anggara-putra/32/ffffff/external-edit-user-interface-anggara-glyph-anggara-putra.png">
                <div class="hidden lg:block text-white rounded-full font-bold">New Message</div>
            </a>
        </div>

        <div x-show="modal_open" x-cloak class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">
            <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>
            <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
              <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
                <div class="relative transform overflow-hidden rounded-2xl bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
                  <div @click.away="modal_open = false" class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">

                    {% include 'a_inbox/form_searchuser.html' %}
                        
                  </div>
                </div>
              </div>
            </div>
          </div>

          {% include 'a_inbox/my_conversations.html' %}

    </div>
    {% include 'a_inbox/conversation.html' %}
</inbox>


<script>
    function scrollToBottom() {
            const container = document.getElementById('conversation');
            container.scrollTop = container.scrollHeight;
        }

    window.onload = function() {
        scrollToBottom();
    };
</script>

{% endblock %}

a_inbox/templates/a_inbox/list_searchuser.html
<ul id="user-list" class="mt-2">
    {% for user in users %}
    <li>
        <a class="flex items-center gap-1 hover:bg-zinc-100 rounded-lg p-2 cursor-pointer"
        hx-get="{% url 'inbox-newmessage' user.id %}"
        hx-target="#new-message"
        hx-swap="innerHTML" >
            <img class="w-10 h-10 object-cover rounded-full mr-1" src="{{ user.profile.avatar }}">
            <div class="font-bold">{{ user.profile.name }} <span class="text-xs font-normal text-zinc-500">@{{ user.username }}</span></div>
        </a>
    </li>
  {% endfor %}
</ul>

a_inbox/templates/a_inbox/my_conversations.html
<ul id="conversations-list" class="flex flex-col gap-1 divide-y mt-2" >
    {% for c in my_conversations %}
    <li class="{% if conversation == c %}bg-zinc-200{% endif %}rounded-full sm:rounded-lg relative mt-2 sm:mt-0">
        <a href="{% url 'inbox' c.id %}" class="flex items-center justify-center lg:justify-normal gap-1 hover:bg-zinc-200 rounded-full sm:rounded-lg p-1.5 sm:p-4 cursor-pointer">
            {% for participant in c.participants.all %}
            {% if participant != request.user %}

            <div class="absolute top-3 left-11 [&>*]:border-2 [&>*]:border-gray-100"
                hx-get="{% url 'notify-newmessage' c.id %}"
                hx-trigger="load"
                hx-target="this"
                hx-swap="innerHTML" >
            </div>

            <img class="w-11 h-11 lg:w-10 lg:h-10 object-cover rounded-full" src="{{ participant.profile.avatar }}">
            <div class="hidden lg:block font-bold ml-1">{{ participant.profile.name }}</div>
            {% endif %}
            {% endfor %}
        </a>
    </li>
    {% endfor %}
</ul>

a_inbox/templates/a_inbox/notify_icon.html
<div class="rounded-full bg-blue-500 p-1.5"></div>